server:
  port: 8080

spring:
  application:
    name: ab-java-react-back
  datasource:
    url: jdbc:sqlite:data/app.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

app:
  cors:
    allowed-origins: "http://localhost:5173"
